exports.seed = function (knex, Promise) {
  return knex('movie_tests').del()
    .then(function () {
      return knex('movie_tests').insert([
        { id: 1, test_type: 'Bechdel Test', movie_id: 1, result: true },
        { id: 2, test_type: 'Rees Davies Test', movie_id: 1, result: false },
        { id: 3, test_type: 'Ko Test', movie_id: 1, result: true },
        { id: 4, test_type: 'Landau Test', movie_id: 1, result: true },
        { id: 5, test_type: 'Feldman Test', movie_id: 1, result: false },

        { id: 6, test_type: 'Bechdel Test', movie_id: 2, result: true },
        { id: 7, test_type: 'Rees Davies Test', movie_id: 2, result: false },
        { id: 8, test_type: 'Ko Test', movie_id: 2, result: true },
        { id: 9, test_type: 'Landau Test', movie_id: 2, result: true },
        { id: 10, test_type: 'Feldman Test', movie_id: 2, result: true },

        { id: 11, test_type: 'Bechdel Test', movie_id: 3, result: true },
        { id: 12, test_type: 'Rees Davies Test', movie_id: 3, result: false },
        { id: 13, test_type: 'Ko Test', movie_id: 3, result: true },
        { id: 14, test_type: 'Landau Test', movie_id: 3, result: false },
        { id: 15, test_type: 'Feldman Test', movie_id: 3, result: true },

        { id: 16, test_type: 'Bechdel Test', movie_id: 4, result: true },
        { id: 17, test_type: 'Rees Davies Test', movie_id: 4, result: true },
        { id: 18, test_type: 'Ko Test', movie_id: 4, result: false },
        { id: 19, test_type: 'Landau Test', movie_id: 4, result: false },
        { id: 20, test_type: 'Feldman Test', movie_id: 4, result: true },

        { id: 21, test_type: 'Bechdel Test', movie_id: 5, result: true },
        { id: 22, test_type: 'Rees Davies Test', movie_id: 5, result: false },
        { id: 23, test_type: 'Ko Test', movie_id: 5, result: true },
        { id: 24, test_type: 'Landau Test', movie_id: 5, result: true },
        { id: 25, test_type: 'Feldman Test', movie_id: 5, result: true },

        { id: 26, test_type: 'Bechdel Test', movie_id: 6, result: true },
        { id: 27, test_type: 'Rees Davies Test', movie_id: 6, result: false },
        { id: 28, test_type: 'Ko Test', movie_id: 6, result: true },
        { id: 29, test_type: 'Landau Test', movie_id: 6, result: false },
        { id: 30, test_type: 'Feldman Test', movie_id: 6, result: true },

        { id: 31, test_type: 'Bechdel Test', movie_id: 7, result: true },
        { id: 32, test_type: 'Rees Davies Test', movie_id: 7, result: false },
        { id: 33, test_type: 'Ko Test', movie_id: 7, result: false },
        { id: 34, test_type: 'Landau Test', movie_id: 7, result: false },
        { id: 35, test_type: 'Feldman Test', movie_id: 7, result: true },

        { id: 36, test_type: 'Bechdel Test', movie_id: 8, result: true },
        { id: 37, test_type: 'Rees Davies Test', movie_id: 8, result: true },
        { id: 38, test_type: 'Ko Test', movie_id: 8, result: true },
        { id: 39, test_type: 'Landau Test', movie_id: 8, result: true },
        { id: 40, test_type: 'Feldman Test', movie_id: 8, result: false },

        { id: 41, test_type: 'Bechdel Test', movie_id: 9, result: true },
        { id: 42, test_type: 'Rees Davies Test', movie_id: 9, result: true },
        { id: 43, test_type: 'Ko Test', movie_id: 9, result: true },
        { id: 44, test_type: 'Landau Test', movie_id: 9, result: true },
        { id: 45, test_type: 'Feldman Test', movie_id: 9, result: true },

        { id: 46, test_type: 'Bechdel Test', movie_id: 10, result: true },
        { id: 47, test_type: 'Rees Davies Test', movie_id: 10, result: false },
        { id: 48, test_type: 'Ko Test', movie_id: 10, result: false },
        { id: 49, test_type: 'Landau Test', movie_id: 10, result: true },
        { id: 50, test_type: 'Feldman Test', movie_id: 10, result: true },

        { id: 51, test_type: 'Bechdel Test', movie_id: 11, result: true },
        { id: 52, test_type: 'Rees Davies Test', movie_id: 11, result: true },
        { id: 53, test_type: 'Ko Test', movie_id: 11, result: true },
        { id: 54, test_type: 'Landau Test', movie_id: 11, result: false },
        { id: 55, test_type: 'Feldman Test', movie_id: 11, result: false },

        { id: 56, test_type: 'Bechdel Test', movie_id: 12, result: true },
        { id: 57, test_type: 'Rees Davies Test', movie_id: 12, result: false },
        { id: 58, test_type: 'Ko Test', movie_id: 12, result: false },
        { id: 59, test_type: 'Landau Test', movie_id: 12, result: true },
        { id: 60, test_type: 'Feldman Test', movie_id: 12, result: true },

        { id: 61, test_type: 'Bechdel Test', movie_id: 13, result: true },
        { id: 62, test_type: 'Rees Davies Test', movie_id: 13, result: false },
        { id: 63, test_type: 'Ko Test', movie_id: 13, result: false },
        { id: 64, test_type: 'Landau Test', movie_id: 13, result: false },
        { id: 65, test_type: 'Feldman Test', movie_id: 13, result: true },

        { id: 66, test_type: 'Bechdel Test', movie_id: 14, result: true },
        { id: 67, test_type: 'Rees Davies Test', movie_id: 14, result: false },
        { id: 68, test_type: 'Ko Test', movie_id: 14, result: true },
        { id: 69, test_type: 'Landau Test', movie_id: 14, result: false },
        { id: 70, test_type: 'Feldman Test', movie_id: 14, result: false },

        { id: 71, test_type: 'Bechdel Test', movie_id: 15, result: true },
        { id: 72, test_type: 'Rees Davies Test', movie_id: 15, result: true },
        { id: 73, test_type: 'Ko Test', movie_id: 15, result: false },
        { id: 74, test_type: 'Landau Test', movie_id: 15, result: false },
        { id: 75, test_type: 'Feldman Test', movie_id: 15, result: true },

        { id: 76, test_type: 'Bechdel Test', movie_id: 16, result: true },
        { id: 77, test_type: 'Rees Davies Test', movie_id: 16, result: false },
        { id: 78, test_type: 'Ko Test', movie_id: 16, result: true },
        { id: 79, test_type: 'Landau Test', movie_id: 16, result: false },
        { id: 80, test_type: 'Feldman Test', movie_id: 16, result: false },

        { id: 81, test_type: 'Bechdel Test', movie_id: 17, result: true },
        { id: 82, test_type: 'Rees Davies Test', movie_id: 17, result: false },
        { id: 83, test_type: 'Ko Test', movie_id: 17, result: false },
        { id: 84, test_type: 'Landau Test', movie_id: 17, result: false },
        { id: 85, test_type: 'Feldman Test', movie_id: 17, result: false },

        { id: 86, test_type: 'Bechdel Test', movie_id: 18, result: false },
        { id: 87, test_type: 'Rees Davies Test', movie_id: 18, result: false },
        { id: 88, test_type: 'Ko Test', movie_id: 18, result: true },
        { id: 89, test_type: 'Landau Test', movie_id: 18, result: true },
        { id: 90, test_type: 'Feldman Test', movie_id: 18, result: false },

        { id: 91, test_type: 'Bechdel Test', movie_id: 19, result: false },
        { id: 92, test_type: 'Rees Davies Test', movie_id: 19, result: false },
        { id: 93, test_type: 'Ko Test', movie_id: 19, result: false },
        { id: 94, test_type: 'Landau Test', movie_id: 19, result: true },
        { id: 95, test_type: 'Feldman Test', movie_id: 19, result: false },

        { id: 96, test_type: 'Bechdel Test', movie_id: 20, result: true },
        { id: 97, test_type: 'Rees Davies Test', movie_id: 20, result: true },
        { id: 98, test_type: 'Ko Test', movie_id: 20, result: false },
        { id: 99, test_type: 'Landau Test', movie_id: 20, result: false },
        { id: 100, test_type: 'Feldman Test', movie_id: 20, result: true },

        { id: 101, test_type: 'Bechdel Test', movie_id: 21, result: true },
        { id: 102, test_type: 'Rees Davies Test', movie_id: 21, result: true },
        { id: 103, test_type: 'Ko Test', movie_id: 21, result: true },
        { id: 104, test_type: 'Landau Test', movie_id: 21, result: false },
        { id: 105, test_type: 'Feldman Test', movie_id: 21, result: false },

        { id: 106, test_type: 'Bechdel Test', movie_id: 22, result: false },
        { id: 107, test_type: 'Rees Davies Test', movie_id: 22, result: true },
        { id: 108, test_type: 'Ko Test', movie_id: 22, result: false },
        { id: 109, test_type: 'Landau Test', movie_id: 22, result: false },
        { id: 110, test_type: 'Feldman Test', movie_id: 22, result: false },

        { id: 111, test_type: 'Bechdel Test', movie_id: 23, result: true },
        { id: 112, test_type: 'Rees Davies Test', movie_id: 23, result: true },
        { id: 113, test_type: 'Ko Test', movie_id: 23, result: true },
        { id: 114, test_type: 'Landau Test', movie_id: 23, result: false },
        { id: 115, test_type: 'Feldman Test', movie_id: 23, result: false },

        { id: 116, test_type: 'Bechdel Test', movie_id: 24, result: true },
        { id: 117, test_type: 'Rees Davies Test', movie_id: 24, result: false },
        { id: 118, test_type: 'Ko Test', movie_id: 24, result: false },
        { id: 119, test_type: 'Landau Test', movie_id: 24, result: false },
        { id: 120, test_type: 'Feldman Test', movie_id: 24, result: false },

        { id: 121, test_type: 'Bechdel Test', movie_id: 25, result: true },
        { id: 122, test_type: 'Rees Davies Test', movie_id: 25, result: false },
        { id: 123, test_type: 'Ko Test', movie_id: 25, result: true },
        { id: 124, test_type: 'Landau Test', movie_id: 25, result: false },
        { id: 125, test_type: 'Feldman Test', movie_id: 25, result: false },

        { id: 126, test_type: 'Bechdel Test', movie_id: 26, result: true },
        { id: 127, test_type: 'Rees Davies Test', movie_id: 26, result: false },
        { id: 128, test_type: 'Ko Test', movie_id: 26, result: false },
        { id: 129, test_type: 'Landau Test', movie_id: 26, result: true },
        { id: 130, test_type: 'Feldman Test', movie_id: 26, result: false },

        { id: 131, test_type: 'Bechdel Test', movie_id: 27, result: true },
        { id: 132, test_type: 'Rees Davies Test', movie_id: 27, result: false },
        { id: 133, test_type: 'Ko Test', movie_id: 27, result: false },
        { id: 134, test_type: 'Landau Test', movie_id: 27, result: false },
        { id: 135, test_type: 'Feldman Test', movie_id: 27, result: false },

        { id: 136, test_type: 'Bechdel Test', movie_id: 28, result: false },
        { id: 137, test_type: 'Rees Davies Test', movie_id: 28, result: true },
        { id: 138, test_type: 'Ko Test', movie_id: 28, result: false },
        { id: 139, test_type: 'Landau Test', movie_id: 28, result: false },
        { id: 140, test_type: 'Feldman Test', movie_id: 28, result: false },

        { id: 141, test_type: 'Bechdel Test', movie_id: 29, result: true },
        { id: 142, test_type: 'Rees Davies Test', movie_id: 29, result: true },
        { id: 143, test_type: 'Ko Test', movie_id: 29, result: false },
        { id: 144, test_type: 'Landau Test', movie_id: 29, result: false },
        { id: 145, test_type: 'Feldman Test', movie_id: 29, result: false },

        { id: 146, test_type: 'Bechdel Test', movie_id: 30, result: false },
        { id: 147, test_type: 'Rees Davies Test', movie_id: 30, result: false },
        { id: 148, test_type: 'Ko Test', movie_id: 30, result: true },
        { id: 149, test_type: 'Landau Test', movie_id: 30, result: false },
        { id: 150, test_type: 'Feldman Test', movie_id: 30, result: false },

        { id: 151, test_type: 'Bechdel Test', movie_id: 31, result: true },
        { id: 152, test_type: 'Rees Davies Test', movie_id: 31, result: false },
        { id: 153, test_type: 'Ko Test', movie_id: 31, result: false },
        { id: 154, test_type: 'Landau Test', movie_id: 31, result: false },
        { id: 155, test_type: 'Feldman Test', movie_id: 31, result: false },

        { id: 156, test_type: 'Bechdel Test', movie_id: 32, result: false },
        { id: 157, test_type: 'Rees Davies Test', movie_id: 32, result: true },
        { id: 158, test_type: 'Ko Test', movie_id: 32, result: false },
        { id: 159, test_type: 'Landau Test', movie_id: 32, result: true },
        { id: 160, test_type: 'Feldman Test', movie_id: 32, result: false },

        { id: 161, test_type: 'Bechdel Test', movie_id: 33, result: true },
        { id: 162, test_type: 'Rees Davies Test', movie_id: 33, result: false },
        { id: 163, test_type: 'Ko Test', movie_id: 33, result: false },
        { id: 164, test_type: 'Landau Test', movie_id: 33, result: false },
        { id: 165, test_type: 'Feldman Test', movie_id: 33, result: false },

        { id: 166, test_type: 'Bechdel Test', movie_id: 34, result: true },
        { id: 167, test_type: 'Rees Davies Test', movie_id: 34, result: false },
        { id: 168, test_type: 'Ko Test', movie_id: 34, result: true },
        { id: 169, test_type: 'Landau Test', movie_id: 34, result: false },
        { id: 170, test_type: 'Feldman Test', movie_id: 34, result: false },

        { id: 171, test_type: 'Bechdel Test', movie_id: 35, result: false },
        { id: 172, test_type: 'Rees Davies Test', movie_id: 35, result: false },
        { id: 173, test_type: 'Ko Test', movie_id: 35, result: true },
        { id: 174, test_type: 'Landau Test', movie_id: 35, result: true },
        { id: 175, test_type: 'Feldman Test', movie_id: 35, result: false },

        { id: 176, test_type: 'Bechdel Test', movie_id: 36, result: false },
        { id: 177, test_type: 'Rees Davies Test', movie_id: 36, result: true },
        { id: 178, test_type: 'Ko Test', movie_id: 36, result: true },
        { id: 179, test_type: 'Landau Test', movie_id: 36, result: false },
        { id: 180, test_type: 'Feldman Test', movie_id: 36, result: false },

        { id: 181, test_type: 'Bechdel Test', movie_id: 37, result: false },
        { id: 182, test_type: 'Rees Davies Test', movie_id: 37, result: false },
        { id: 183, test_type: 'Ko Test', movie_id: 37, result: false },
        { id: 184, test_type: 'Landau Test', movie_id: 37, result: true },
        { id: 185, test_type: 'Feldman Test', movie_id: 37, result: false },

        { id: 186, test_type: 'Bechdel Test', movie_id: 38, result: true },
        { id: 187, test_type: 'Rees Davies Test', movie_id: 38, result: false },
        { id: 188, test_type: 'Ko Test', movie_id: 38, result: false },
        { id: 189, test_type: 'Landau Test', movie_id: 38, result: true },
        { id: 190, test_type: 'Feldman Test', movie_id: 38, result: false },

        { id: 191, test_type: 'Bechdel Test', movie_id: 39, result: false },
        { id: 192, test_type: 'Rees Davies Test', movie_id: 39, result: false },
        { id: 193, test_type: 'Ko Test', movie_id: 39, result: true },
        { id: 194, test_type: 'Landau Test', movie_id: 39, result: true },
        { id: 195, test_type: 'Feldman Test', movie_id: 39, result: false },

        { id: 196, test_type: 'Bechdel Test', movie_id: 40, result: false },
        { id: 197, test_type: 'Rees Davies Test', movie_id: 40, result: false },
        { id: 198, test_type: 'Ko Test', movie_id: 40, result: false },
        { id: 199, test_type: 'Landau Test', movie_id: 40, result: true },
        { id: 200, test_type: 'Feldman Test', movie_id: 40, result: false },

        { id: 201, test_type: 'Bechdel Test', movie_id: 41, result: true },
        { id: 202, test_type: 'Rees Davies Test', movie_id: 41, result: false },
        { id: 203, test_type: 'Ko Test', movie_id: 41, result: false },
        { id: 204, test_type: 'Landau Test', movie_id: 41, result: false },
        { id: 205, test_type: 'Feldman Test', movie_id: 41, result: false },

        { id: 206, test_type: 'Bechdel Test', movie_id: 42, result: true },
        { id: 207, test_type: 'Rees Davies Test', movie_id: 42, result: false },
        { id: 208, test_type: 'Ko Test', movie_id: 42, result: false },
        { id: 209, test_type: 'Landau Test', movie_id: 42, result: false },
        { id: 210, test_type: 'Feldman Test', movie_id: 42, result: false },

        { id: 211, test_type: 'Bechdel Test', movie_id: 43, result: false },
        { id: 212, test_type: 'Rees Davies Test', movie_id: 43, result: true },
        { id: 213, test_type: 'Ko Test', movie_id: 43, result: false },
        { id: 214, test_type: 'Landau Test', movie_id: 43, result: false },
        { id: 215, test_type: 'Feldman Test', movie_id: 43, result: false },

        { id: 216, test_type: 'Bechdel Test', movie_id: 44, result: true },
        { id: 217, test_type: 'Rees Davies Test', movie_id: 44, result: false },
        { id: 218, test_type: 'Ko Test', movie_id: 44, result: false },
        { id: 219, test_type: 'Landau Test', movie_id: 44, result: false },
        { id: 220, test_type: 'Feldman Test', movie_id: 44, result: false },

        { id: 221, test_type: 'Bechdel Test', movie_id: 45, result: false },
        { id: 222, test_type: 'Rees Davies Test', movie_id: 45, result: false },
        { id: 223, test_type: 'Ko Test', movie_id: 45, result: true },
        { id: 224, test_type: 'Landau Test', movie_id: 45, result: false },
        { id: 225, test_type: 'Feldman Test', movie_id: 45, result: false },

        { id: 226, test_type: 'Bechdel Test', movie_id: 46, result: false },
        { id: 227, test_type: 'Rees Davies Test', movie_id: 46, result: false },
        { id: 228, test_type: 'Ko Test', movie_id: 46, result: true },
        { id: 229, test_type: 'Landau Test', movie_id: 46, result: true },
        { id: 230, test_type: 'Feldman Test', movie_id: 46, result: false },

        { id: 231, test_type: 'Bechdel Test', movie_id: 47, result: false },
        { id: 232, test_type: 'Rees Davies Test', movie_id: 47, result: false },
        { id: 233, test_type: 'Ko Test', movie_id: 47, result: false },
        { id: 234, test_type: 'Landau Test', movie_id: 47, result: false },
        { id: 235, test_type: 'Feldman Test', movie_id: 47, result: false },

        { id: 236, test_type: 'Bechdel Test', movie_id: 48, result: false },
        { id: 237, test_type: 'Rees Davies Test', movie_id: 48, result: false },
        { id: 238, test_type: 'Ko Test', movie_id: 48, result: false },
        { id: 239, test_type: 'Landau Test', movie_id: 48, result: false },
        { id: 240, test_type: 'Feldman Test', movie_id: 48, result: false },

        { id: 241, test_type: 'Bechdel Test', movie_id: 49, result: false },
        { id: 242, test_type: 'Rees Davies Test', movie_id: 49, result: true },
        { id: 243, test_type: 'Ko Test', movie_id: 49, result: false },
        { id: 244, test_type: 'Landau Test', movie_id: 49, result: false },
        { id: 245, test_type: 'Feldman Test', movie_id: 49, result: false },

        { id: 246, test_type: 'Bechdel Test', movie_id: 50, result: false },
        { id: 247, test_type: 'Rees Davies Test', movie_id: 50, result: false },
        { id: 248, test_type: 'Ko Test', movie_id: 50, result: false },
        { id: 249, test_type: 'Landau Test', movie_id: 50, result: false },
        { id: 250, test_type: 'Feldman Test', movie_id: 50, result: false }
      ])
    })
}
